variables: !include variables-tautrig.yaml

# for k-folded splits, only required for final trainings of GN2
# global_cuts: !include splits/fold0.yaml



signal: &signal
  name: signal
  equal_jets: False
  pattern:
    - "/home/schiavi/workarea/PRE-UPP-DATA/TRIGGER_TAU_FINAL/TTBAR/user.cschiavi.601229.e8514_e8528_s4159_s4114_r15271.tdd.trigger_tau.25_0_24.r12684_r12782.v0-615-gdd5e560_output.h5/user.cschiavi.43361635._000001.output.h5"
    - "/home/schiavi/workarea/PRE-UPP-DATA/TRIGGER_TAU_FINAL/GAMMATAUTAU/user.cschiavi.801002.e8514_e8528_s4159_s4114_r15271.tdd.trigger_tau.25_0_24.r12684_r12782.v0-615-gdd5e560_output.h5/user.cschiavi.43361636._000002.output.h5"
    - "/home/schiavi/workarea/PRE-UPP-DATA/TRIGGER_TAU_FINAL/ZTAUTAU_PHPY/user.cschiavi.601191.e8514_e8528_s4159_s4114_r15271.tdd.trigger_tau.25_0_24.r12684_r12782.v0-615-gdd5e560_output.h5/user.cschiavi.43367656._000001.output.h5"


background: &background
  name: background
  equal_jets: False
  pattern:
    - "/home/schiavi/workarea/PRE-UPP-DATA/TRIGGER_TAU_FINAL/JZ1/user.cschiavi.801166.e8514_e8528_s4159_s4114_r15271.tdd.trigger_tau.25_0_24.r12684_r12782.v0-615-gdd5e560_output.h5/user.cschiavi.43367659._000001.output.h5"
    - "/home/schiavi/workarea/PRE-UPP-DATA/TRIGGER_TAU_FINAL/JZ2/user.cschiavi.801167.e8514_e8528_s4159_s4114_r15271.tdd.trigger_tau.25_0_24.r12684_r12782.v0-615-gdd5e560_output.h5/user.cschiavi.43367660._000001.output.h5"
    - "/home/schiavi/workarea/PRE-UPP-DATA/TRIGGER_TAU_FINAL/JZ3/user.cschiavi.801168.e8514_e8528_s4159_s4114_r15271.tdd.trigger_tau.25_0_24.r12684_r12782.v0-615-gdd5e560_output.h5/user.cschiavi.43370131._000001.output.h5"
    - "/home/schiavi/workarea/PRE-UPP-DATA/TRIGGER_TAU_FINAL/JZ4/user.cschiavi.801169.e8514_e8528_s4159_s4114_r15271.tdd.trigger_tau.25_0_24.r12684_r12782.v0-615-gdd5e560_output.h5/user.cschiavi.43370132._000001.output.h5"



global_cuts:
  train:
    - [eventNumber, "%9<=", 6]
  val:
    - [eventNumber, "%9==", 7]
  test:
    - [eventNumber, "%9==", 8]



inclusive: &inclusive
  name: inclusive
  cuts:
    - [pt, ">", 20_000]
    - [pt, "<", 500_000]
    - [eta, ">", -2.5]
    - [eta, "<", 2.5]



components:

  - region:
      <<: *inclusive
    sample:
      <<: *signal
    flavours: [hadtaujets]
    num_jets: 5_000

  - region:
      <<: *inclusive
    sample:
      <<: *background
    flavours: [qcdjets]
    num_jets: 8_000



resampling:
  target: hadtaujets
  method: pdf
  sampling_fraction: auto
  variables:
    pt:
      bins: [[20_000, 500_000, 30]]
    eta:
      bins: [[-2.5, 2.5, 41]]



# note: sensible defaults are defined in the PreprocessingConfig constructor
global:
  jets_name: jets
  batch_size: 1_000
  num_jets_estimate: 10_000
  base_dir: /home/schiavi/workarea/POST-UPP-DATA/
  ntuple_dir: /home/schiavi/workarea/GNTauTrigger-FINAL/DATA/
