jets:
  inputs:
    - pt
    - eta
    - centFrac
    - isolFrac
    - ptRatioEflowApprox
    - massTrkSys
    - mEflowApprox
    - SumPtTrkFrac
    - absipSigLeadTrk
    - etOverPtLeadTrk
    - innerTrkAvgDist
    - dRmax
    - EMPOverTrkSysP
    - trFlightPathSig
  labels:
    - HadronConeExclTruthLabelID
    - HadronConeExclTruthLabelPt
    - eventNumber
    - IsHadronicTauFromTruthTaus
    - classifierParticleTypeFromTruthTaus
    - numChargedFromTruthTaus
    - nTracks

tau_tracks:
  inputs:
    - pt
    - deta
    - dphi
    - d0TJVA
    - d0SigTJVA
    - z0sinthetaTJVA
    - z0sinthetaSigTJVA
    - numberOfPixelHits
    - numberOfSCTHits
    - numberOfInnermostPixelLayerHits

cells:
  inputs:
    - et
    - dEta
    - dPhi
    - SECOND_LAMBDA
    - CENTER_LAMBDA
    - SECOND_R

