jets:
  inputs:
    - pt
    - eta
    - centFrac
    - isolFrac
    - massTrkSys
    - ptRatioEflowApprox
    - mEflowApprox
    - SumPtTrkFrac
#    - absipSigLeadTrk
    - etOverPtLeadTrk
    - innerTrkAvgDist
    - dRmax
    - EMPOverTrkSysP
    - trFlightPathSig
  labels:
    - HadronConeExclTruthLabelID
    - HadronConeExclTruthLabelPt
    - eventNumber

tau_tracks:
  inputs:
    - d0
    - z0SinTheta
    - d0Uncertainty
    - z0SinThetaUncertainty
    - dphi
    - deta
    - qOverP
    - IP3D_signed_d0
    - IP3D_signed_z0
    - IP3D_signed_d0_significance
    - IP3D_signed_z0_significance
    - phiUncertainty
    - thetaUncertainty
    - qOverPUncertainty
    - numberOfPixelHits
    - numberOfSCTHits
    - numberOfInnermostPixelLayerHits
    - numberOfNextToInnermostPixelLayerHits
#    - numberOfPixelHoles
#    - numberOfSCTHoles
    - d0TJVA
    - d0SigTJVA
    - z0sinthetaTJVA
    - z0sinthetaSigTJVA
    - pt
    - ptfrac
    - qOverPUncertainty

